// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qadjunvqhyhhtwxwwqpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZGp1bnZxaHloaHR3eHd3cXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTQ0NDIsImV4cCI6MjA1ODYzMDQ0Mn0.3h3o5MGqd74C_E1jVhOf7VVTqE9CZquABDLxIcIQYcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);